import "./globals.css";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { DM_Mono } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import { AuthProvider } from "@/components/providers/auth-provider";

const geist = Geist({ subsets: ["latin"] });
const dmMono = DM_Mono({ 
  subsets: ["latin"], 
  weight: ["300", "400", "500"],
  variable: "--font-dm-mono" 
});

export const metadata: Metadata = {
  title: "a8n",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={`${geist.className} ${dmMono.variable} bg-sidebar text-sidebar-foreground`}>
        <AuthProvider>
          {children}
        </AuthProvider>
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
